# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ShopMate"
client_id = "5f758a7af89249a49fc6348ed6bd4666"
application_url = "https://shopmate.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://shopmate.fly.dev/api/auth/callback" ]

[webhooks]
api_version = "2023-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://8sxn47ovn7.execute-api.us-east-1.amazonaws.com/webhooks/customers/redact"
  customer_data_request_url = "https://8sxn47ovn7.execute-api.us-east-1.amazonaws.com/webhooks/customers/data-request"
  shop_deletion_url = "https://8sxn47ovn7.execute-api.us-east-1.amazonaws.com/webhooks/shop/redact"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "ceepul-dev-store.myshopify.com"
